import { NextRequest, NextResponse } from "next/server"
import { z } from "zod"
import { addMinutes } from "date-fns"
import { prisma } from "@/lib/prisma"
import { buildCombo, validateSelection } from "@/lib/services"
import { createEvent } from "@/lib/gcal"
import { formatLisbon } from "@/lib/tz"
import { fixedPriceFor, normalizePhone } from "@/lib/clients"
import {
  sendEmail,
  adminBookingEmail,
  clientReceivedEmail,
  ADMIN_EMAIL,
} from "@/lib/email"

const bodySchema = z.object({
  location: z.enum(["lisboa", "setubal"]),
  /** Array of service item ids, e.g. ["corte", "barba"]. Order doesn't matter. */
  services: z.array(z.string().min(1)).min(1).max(4),
  startUtcIso: z.string().datetime(),
  client: z.object({
    name: z.string().trim().min(2, "Nome demasiado curto").max(80),
    phone: z
      .string()
      .trim()
      .regex(/^[0-9]{9,15}$/, "Telefone deve conter 9-15 dígitos (sem +)"),
    email: z.string().trim().email("Email inválido"),
  }),
  notes: z.string().max(300).optional(),
})

export async function POST(req: NextRequest) {
  let body: unknown
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 })
  }

  const parsed = bodySchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Validation failed", details: parsed.error.format() },
      { status: 400 },
    )
  }

  const { location, services, startUtcIso, notes } = parsed.data
  // Same person typed with or without 351 must end up as one client
  const client = { ...parsed.data.client, phone: normalizePhone(parsed.data.client.phone) }

  const v = validateSelection(services)
  if (!v.ok) return NextResponse.json({ error: v.error }, { status: 400 })

  const combo = buildCombo(services)
  // Some regulars always pay a fixed amount (see lib/clients.ts)
  const price = fixedPriceFor(client.name) ?? combo.priceEur

  const startUtc = new Date(startUtcIso)
  const endUtc = addMinutes(startUtc, combo.durationMin)

  if (startUtc.getTime() <= Date.now()) {
    return NextResponse.json({ error: "Slot no passado" }, { status: 400 })
  }

  // Race-condition safety: re-check no overlapping booking exists
  const overlapping = await prisma.booking.findFirst({
    where: {
      status: { in: ["PENDING", "CONFIRMED"] },
      startUtc: { lt: endUtc },
      endUtc: { gt: startUtc },
    },
    select: { id: true },
  })
  if (overlapping) {
    return NextResponse.json(
      { error: "Esse horário foi marcado entretanto. Escolhe outro." },
      { status: 409 },
    )
  }

  // Upsert client by phone
  const dbClient = await prisma.client.upsert({
    where: { phone: client.phone },
    update: { name: client.name, email: client.email },
    create: { phone: client.phone, name: client.name, email: client.email },
  })

  // Create booking — adminToken/clientToken auto-generated by Prisma defaults
  const booking = await prisma.booking.create({
    data: {
      clientId: dbClient.id,
      email: client.email,
      serviceId: combo.key,
      serviceName: combo.name,
      servicePrice: price,
      durationMin: combo.durationMin,
      location,
      startUtc,
      endUtc,
      status: "PENDING",
      notes,
    },
  })

  const whenLocal = formatLisbon(startUtc, "EEEE, dd 'de' MMMM 'às' HH:mm")
  const locationPretty = location === "lisboa" ? "Lisboa" : "Setúbal"

  // Send admin notification email (best effort — booking still proceeds if it fails)
  try {
    const tpl = adminBookingEmail({
      id: booking.id,
      clientName: client.name,
      clientPhone: client.phone,
      clientEmail: client.email,
      serviceName: combo.name,
      durationMin: combo.durationMin,
      priceEur: price,
      location: locationPretty,
      whenLocal,
      startUtc,
      endUtc,
      notes: notes ?? null,
      adminToken: booking.adminToken,
      clientToken: booking.clientToken,
    })
    await sendEmail({ to: ADMIN_EMAIL, subject: tpl.subject, html: tpl.html })
  } catch (e) {
    console.error("[bookings] admin email failed:", e)
  }

  // Send "we received your booking" email to the client (best effort)
  try {
    const tpl = clientReceivedEmail({
      id: booking.id,
      clientName: client.name,
      clientPhone: client.phone,
      clientEmail: client.email,
      serviceName: combo.name,
      durationMin: combo.durationMin,
      priceEur: price,
      location: locationPretty,
      whenLocal,
      startUtc,
      endUtc,
      notes: notes ?? null,
      adminToken: booking.adminToken,
      clientToken: booking.clientToken,
    })
    await sendEmail({ to: client.email, subject: tpl.subject, html: tpl.html })
  } catch (e) {
    console.error("[bookings] client received email failed:", e)
  }

  // Best-effort GCal sync
  try {
    const eventId = await createEvent({
      summary: `[PENDENTE] ${combo.name} - ${client.name}`,
      description:
        `Cliente: ${client.name}\n` +
        `Telefone: ${client.phone}\n` +
        `Email: ${client.email}\n` +
        `Serviço: ${combo.name} (${combo.durationMin}min — ${price}€)\n` +
        (notes ? `Notas: ${notes}\n` : "") +
        `\nID: ${booking.id}`,
      location: locationPretty,
      startUtc,
      endUtc,
    })
    if (eventId) {
      await prisma.booking.update({
        where: { id: booking.id },
        data: { gcalEventId: eventId },
      })
    }
  } catch (e) {
    console.error("[bookings] gcal create failed:", e)
  }

  return NextResponse.json({
    ok: true,
    booking: {
      id: booking.id,
      clientToken: booking.clientToken,
      location,
      service: combo.name,
      priceEur: price,
      whenLocal,
      startUtcIso: startUtc.toISOString(),
    },
  })
}
